#!/bin/bash -eux

PRODUCT=$1     # QS or AYA
ENVIRONMENT=$2 # PRODUCTION or STAGING
eval "export AWS_DEFAULT_REGION=\$${PRODUCT}_AWS_DEFAULT_REGION"
eval "export AWS_ACCESS_KEY_ID=\$${PRODUCT}_AWS_ACCESS_KEY_ID"
eval "export AWS_SECRET_ACCESS_KEY=\$${PRODUCT}_AWS_SECRET_ACCESS_KEY"
eval "export DEIS_USER=\$${PRODUCT}_DEIS_USER_${ENVIRONMENT}"
eval "export DEIS_PLATFORM_DOMAIN=\$${PRODUCT}_DEIS_PLATFORM_DOMAIN_${ENVIRONMENT}"
eval "export DEIS_API_TOKEN=\$${PRODUCT}_DEIS_API_TOKEN_${ENVIRONMENT}"
eval "export DEIS_SSH_SECURITY_GROUP_ID=\$${PRODUCT}_DEIS_SSH_SECURITY_GROUP_ID_${ENVIRONMENT}"
